<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RetailLab.Core\RetailLab.Core.csproj" />
    <ProjectReference Include="..\RetailLab.Data\RetailLab.Data.csproj" />
  </ItemGroup>

</Project>
